version: '3.9'

services:
  nginx:
    build: ./config/nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./my-project/public:/var/www/html/public:ro
      - ./my-project/themes:/var/www/html/themes:ro
      - ./my-project/vendor:/var/www/html/vendor:ro
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  web:
    build: .
    environment:
      SS_DATABASE_CLASS: "MySQLDatabase"
      SS_DATABASE_NAME: "ss_demo"
      SS_DATABASE_SERVER: "db"
      SS_DATABASE_USERNAME: "admin"
      SS_DATABASE_PASSWORD: "password"
      SS_DEFAULT_ADMIN_USERNAME: "admin"
      SS_DEFAULT_ADMIN_PASSWORD: "password"
      SS_ENVIRONMENT_TYPE: "dev"
    volumes:
      - ./my-project:/var/www/html/
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro

  db:
    image: mysql:8-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ss_demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}
